### ISSUE TITLE
@1.1.1 cannot find name 'Quill'

### ISSUE THREAD

**Issue by manofearth** [surmon-china/ng2-quill-editor#6]
have an error
```
quillEditor.component.ts:79:28 Cannot find name 'Quill'.
```
after update 1.1.0 to 1.1.1

**Comment by prosenjit-itobuz** [comment]
Create a new file typings.d.ts inside src and add below code

```
declare var require: any;
declare var module: any;

```

**Comment by summitmman** [comment]
Hi,

I am using angular-cli@1.0.0-rc.0 and ng2-quill-editor@1.1.1, and i am getting the same error. I tried adding typings.d.ts file (as mentioned above) in my project src folder (I also tried adding it to the node_modules ng2-quill-editor folder), but that did not solve the error.

Am I supposed to add it somewhere else. Why is this file required??
Please help

Thanks

**Comment by prosenjit-itobuz** [comment]
update angular cli @angular/cli: 1.0.0-beta.32.3 and check.

**Comment by summitmman** [comment]
Hi I cannot really downgrade angular-cli. It will be really helpful if this was fixed for the latest version of angular-cli.

Thanks anyway

**Comment by wengjincheng** [comment]
`EXCEPTION: Uncaught (in promise): Error: Error in ./QuillEditorComponentExample01 class QuillEditorComponentExample01 - inline template:0:0 caused by: Quill is not defined
Error: Error in ./QuillEditorComponentExample01 class QuillEditorComponentExample01 - inline template:0:0 caused by: Quill is not defined
    at ViewWrappedError.ZoneAwareError (http://localhost:4200/polyfills.bundle.js:3236:33)
    at ViewWrappedError.BaseError [as constructor] (http://localhost:4200/vendor.bundle.js:29017:16)
    at ViewWrappedError.WrappedError [as constructor] (http://localhost:4200/vendor.bundle.js:29082:16)
    at new ViewWrappedError (http://localhost:4200/vendor.bundle.js:58697:16)
    at CompiledTemplate.proxyViewClass.DebugAppView._rethrowWithContext (http://localhost:4200/vendor.bundle.js:79752:23)
    at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (http://localhost:4200/vendor.bundle.js:79725:18)
    at CompiledTemplate.proxyViewClass.AppView.internalDetectChanges (http://localhost:4200/vendor.bundle.js:79512:18)
    at CompiledTemplate.proxyViewClass.View_QuillEditorComponentExample01_Host0.detectChangesInternal (/AppModule/QuillEditorComponentExample01/host.ngfactory.js:29:19)
    at CompiledTemplate.proxyViewClass.AppView.detectChanges (http://localhost:4200/vendor.bundle.js:79527:14)
    at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (http://localhost:4200/vendor.bundle.js:79722:44)
    at ViewRef_.detectChanges (http://localhost:4200/vendor.bundle.js:59624:20)
    at RouterOutlet.activate (http://localhost:4200/vendor.bundle.js:65180:42)
    at ActivateRoutes.placeComponentIntoOutlet (http://localhost:4200/vendor.bundle.js:24098:16)
    at ActivateRoutes.activateRoutes (http://localhost:4200/vendor.bundle.js:24065:26)
    at http://localhost:4200/vendor.bundle.js:24001:58
ErrorHandler.handleError @ error_handler.js:54
next @ application_ref.js:348
schedulerFn @ async.js:93
SafeSubscriber.__tryOrUnsub @ Subscriber.js:234
SafeSubscriber.next @ Subscriber.js:183
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ async.js:79
NgZone.triggerError @ ng_zone.js:333
onHandleError @ ng_zone.js:294
webpackJsonp.617.ZoneDelegate.handleError @ zone.js:334
webpackJsonp.617.Zone.runGuarded @ zone.js:142
_loop_1 @ zone.js:540
drainMicroTaskQueue @ zone.js:549
error_handler.js:59ORIGINAL STACKTRACE:
ErrorHandler.handleError @ error_handler.js:59
next @ application_ref.js:348
schedulerFn @ async.js:93
SafeSubscriber.__tryOrUnsub @ Subscriber.js:234
SafeSubscriber.next @ Subscriber.js:183
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ async.js:79
NgZone.triggerError @ ng_zone.js:333
onHandleError @ ng_zone.js:294
webpackJsonp.617.ZoneDelegate.handleError @ zone.js:334
webpackJsonp.617.Zone.runGuarded @ zone.js:142
_loop_1 @ zone.js:540
drainMicroTaskQueue @ zone.js:549
error_handler.js:60Error: Uncaught (in promise): Error: Error in ./QuillEditorComponentExample01 class QuillEditorComponentExample01 - inline template:0:0 caused by: Quill is not defined
Error: Error in ./QuillEditorComponentExample01 class QuillEditorComponentExample01 - inline template:0:0 caused by: Quill is not defined
    at ViewWrappedError.ZoneAwareError (zone.js:958)
    at ViewWrappedError.BaseError [as constructor] (errors.js:22)
    at ViewWrappedError.WrappedError [as constructor] (errors.js:87)
    at new ViewWrappedError (errors.js:77)
    at CompiledTemplate.proxyViewClass.DebugAppView._rethrowWithContext (view.js:650)
    at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (view.js:623)
    at CompiledTemplate.proxyViewClass.AppView.internalDetectChanges (view.js:410)
    at CompiledTemplate.proxyViewClass.View_QuillEditorComponentExample01_Host0.detectChangesInternal (/AppModule/QuillEditorComponentExample01/host.ngfactory.js:29)
    at CompiledTemplate.proxyViewClass.AppView.detectChanges (view.js:425)
    at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (view.js:620)
    at ViewRef_.detectChanges (view_ref.js:170)
    at RouterOutlet.activate (router_outlet.js:156)
    at ActivateRoutes.placeComponentIntoOutlet (router.js:1348)
    at ActivateRoutes.activateRoutes (router.js:1315)
    at router.js:1251
    at resolvePromise (zone.js:643) [angular]
    at resolvePromise (zone.js:619) [angular]
    at polyfills.bundle.js:2957:17 [angular]
    at Object.onInvokeTask (ng_zone.js:264) [angular]
    at ZoneDelegate.webpackJsonp.617.ZoneDelegate.invokeTask (zone.js:362) [angular]
    at Zone.webpackJsonp.617.Zone.runTask (zone.js:166) [<root> => angular]
    at drainMicroTaskQueue (zone.js:529) [<root>]
ErrorHandler.handleError @ error_handler.js:60
next @ application_ref.js:348
schedulerFn @ async.js:93
SafeSubscriber.__tryOrUnsub @ Subscriber.js:234
SafeSubscriber.next @ Subscriber.js:183
Subscriber._next @ Subscriber.js:125
Subscriber.next @ Subscriber.js:89
Subject.next @ Subject.js:55
EventEmitter.emit @ async.js:79
NgZone.triggerError @ ng_zone.js:333
onHandleError @ ng_zone.js:294
webpackJsonp.617.ZoneDelegate.handleError @ zone.js:334
webpackJsonp.617.Zone.runGuarded @ zone.js:142
_loop_1 @ zone.js:540
drainMicroTaskQueue @ zone.js:549
zone.js:516Unhandled Promise rejection: Error in ./QuillEditorComponentExample01 class QuillEditorComponentExample01 - inline template:0:0 caused by: Quill is not defined ; Zone: angular ; Task: Promise.then ; Value: ViewWrappedError {__zone_symbol__error: Error: Error in ./QuillEditorComponentExample01 class QuillEditorComponentExample01 - inline templat…, _nativeError: ZoneAwareError, originalError: ReferenceError: Quill is not defined
    at QuillEditorComponent.ngAfterViewInit (http://localhost:4…, context: DebugContext, __zone_symbol__stack: "Error: Error in ./QuillEditorComponentExample01 cl…t http://localhost:4200/vendor.bundle.js:24001:58"…} Error: Error in ./QuillEditorComponentExample01 class QuillEditorComponentExample01 - inline template:0:0 caused by: Quill is not defined
    at ViewWrappedError.ZoneAwareError (http://localhost:4200/polyfills.bundle.js:3236:33)
    at ViewWrappedError.BaseError [as constructor] (http://localhost:4200/vendor.bundle.js:29017:16)
    at ViewWrappedError.WrappedError [as constructor] (http://localhost:4200/vendor.bundle.js:29082:16)
    at new ViewWrappedError (http://localhost:4200/vendor.bundle.js:58697:16)
    at CompiledTemplate.proxyViewClass.DebugAppView._rethrowWithContext (http://localhost:4200/vendor.bundle.js:79752:23)
    at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (http://localhost:4200/vendor.bundle.js:79725:18)
    at CompiledTemplate.proxyViewClass.AppView.internalDetectChanges (http://localhost:4200/vendor.bundle.js:79512:18)
    at CompiledTemplate.proxyViewClass.View_QuillEditorComponentExample01_Host0.detectChangesInternal (/AppModule/QuillEditorComponentExample01/host.ngfactory.js:29:19)
    at CompiledTemplate.proxyViewClass.AppView.detectChanges (http://localhost:4200/vendor.bundle.js:79527:14)
    at CompiledTemplate.proxyViewClass.DebugAppView.detectChanges (http://localhost:4200/vendor.bundle.js:79722:44)
    at ViewRef_.detectChanges (http://localhost:4200/vendor.bundle.js:59624:20)
    at RouterOutlet.activate (http://localhost:4200/vendor.bundle.js:65180:42)
    at ActivateRoutes.placeComponentIntoOutlet (http://localhost:4200/vendor.bundle.js:24098:16)
    at ActivateRoutes.activateRoutes (http://localhost:4200/vendor.bundle.js:24065:26)
    at http://localhost:4200/vendor.bundle.js:24001:58` 
I alse have this issue,Quill is not defined . And i create typings.d.ts in src and write code you say .
unfortunately, it is not work .

**Comment by bmdatl** [comment]
@wengjincheng I am having the same issue, Quill is not defined. 

Have you been able to fix it yet?

**Comment by surmon-china** [comment]
v2.0.0 will fix it.
